// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadDatabase() {
  return window['go']['main']['App']['LoadDatabase']();
}

export function PagePrint() {
  return window['go']['main']['App']['PagePrint']();
}
