// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function LoadDatabase():Promise<db.Database>;

export function PagePrint():Promise<void>;
